Attribute VB_Name = "ShowOrganizerStyles"
' Shows the same list of available styles as in "Organizer".
' The "Organizer" dialog in Word shows only the styles that are currently in use or have been modified in the document, rather than all available styles. Let's update the macro to reflect this.
' Generated by Microsoft Copilot M365 by ms on 2025-01-28.

Sub ShowOrganizerStyles()
    Dim doc As Document
    Dim template As template
    Dim templatePath As String
    Dim style As style
    Dim styleInfo As String
    Dim filePath As String
    Dim fileNum As Integer
    Dim counter As Integer
    Dim currentDate As String
    Dim currentTime As String
    Dim docName As String
    Dim macroName As String
    
    ' Get the currently active document
    Set doc = ActiveDocument
    
    ' Get the template attached to the document
    Set template = doc.AttachedTemplate
    templatePath = template.FullName
    
    ' Initialize the style information string
    styleInfo = "No. | Style Name | Type | Built-in" & vbCrLf
    counter = 1
    
    ' Loop through all styles in the document
    For Each style In doc.Styles
        If style.InUse Then
            styleInfo = styleInfo & counter & " | " & _
                        style.NameLocal & " | " & _
                        StyleTypeName(style.Type) & " | " & _
                        CStr(style.BuiltIn) & vbCrLf
            counter = counter + 1
        End If
    Next style
    
    ' Get current date and time
    currentDate = Format(Date, "yyyy-mm-dd")
    currentTime = Format(Time, "hh:mm")
    
    ' Get document name and macro name
    docName = doc.Name
    macroName = "ShowOrganizerStyles"
    
    ' Get the path to the folder of the currently active document
    filePath = doc.Path & "\OrganizerStylesList.txt"
    
    ' Write the style information to the text file
    fileNum = FreeFile
    Open filePath For Output As fileNum
    Print #fileNum, "Document Name: " & docName
    Print #fileNum, "Template Name: " & templatePath
    Print #fileNum, "Macro Name: " & macroName
    Print #fileNum, "Date: " & currentDate
    Print #fileNum, "Time: " & currentTime
    Print #fileNum, vbCrLf & styleInfo
    Close fileNum
    
    ' Inform the user that the styles have been logged
    MsgBox "The styles have been logged to " & filePath, vbInformation, "Styles Logged"
End Sub

Function StyleTypeName(styleType As WdStyleType) As String
    Select Case styleType
        Case wdStyleTypeParagraph
            StyleTypeName = "Paragraph"
        Case wdStyleTypeCharacter
            StyleTypeName = "Character"
        Case wdStyleTypeTable
            StyleTypeName = "Table"
        Case wdStyleTypeList
            StyleTypeName = "List"
        Case Else
            StyleTypeName = "Unknown"
    End Select
End Function

